-- MySQL Script generated by MySQL Workbench
-- sáb 26 sep 2020 10:09:10 -04
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema enterprise
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema enterprise
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `enterprise` DEFAULT CHARACTER SET latin1 ;
USE `enterprise` ;

-- -----------------------------------------------------
-- Table `enterprise`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `enterprise`.`categoria` (
  `idCategoria` INT(11) NOT NULL AUTO_INCREMENT,
  `categoria` VARCHAR(25) NOT NULL,
  `estatusCategoria` CHAR(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`idCategoria`))
ENGINE = InnoDB
AUTO_INCREMENT = 28
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `enterprise`.`articulo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `enterprise`.`articulo` (
  `idArticulo` INT(11) NOT NULL AUTO_INCREMENT,
  `idCategoria` INT(11) NOT NULL,
  `nombre` VARCHAR(55) NOT NULL,
  `precio` INT(11) NOT NULL,
  `fechaIngreso` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `stock` INT(11) NOT NULL,
  `estatusArticulo` CHAR(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`idArticulo`),
  INDEX `fk_articulo_categoria1_idx` (`idCategoria` ASC),
  CONSTRAINT `fk_articulo_categoria1`
    FOREIGN KEY (`idCategoria`)
    REFERENCES `enterprise`.`categoria` (`idCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 25
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `enterprise`.`persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `enterprise`.`persona` (
  `idPersona` INT(11) NOT NULL AUTO_INCREMENT,
  `nombrePersona` VARCHAR(100) NOT NULL,
  `apellidoPersona` VARCHAR(100) NOT NULL,
  `correoPersona` VARCHAR(55) NOT NULL,
  `estatusPersona` CHAR(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`idPersona`))
ENGINE = InnoDB
AUTO_INCREMENT = 26
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `enterprise`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `enterprise`.`cliente` (
  `idCliente` INT(11) NOT NULL AUTO_INCREMENT,
  `idPersona` INT(11) NOT NULL,
  `descuento` FLOAT NOT NULL,
  `estatusCliente` CHAR(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`idCliente`),
  INDEX `idPersona` (`idPersona` ASC),
  CONSTRAINT `cliente_ibfk_1`
    FOREIGN KEY (`idPersona`)
    REFERENCES `enterprise`.`persona` (`idPersona`))
ENGINE = InnoDB
AUTO_INCREMENT = 14
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `enterprise`.`pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `enterprise`.`pedido` (
  `idPedido` INT(11) NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(55) NOT NULL,
  `fecha` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `fechaEntrega` DATE NOT NULL,
  `estatusPedido` CHAR(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`idPedido`))
ENGINE = InnoDB
AUTO_INCREMENT = 17
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `enterprise`.`factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `enterprise`.`factura` (
  `idPedidoCliente` INT(11) NOT NULL AUTO_INCREMENT,
  `idPedido` INT(11) NOT NULL,
  `idCliente` INT(11) NOT NULL,
  `totalAPagar` FLOAT NOT NULL,
  `estatusPedidocliente` CHAR(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`idPedidoCliente`),
  INDEX `idPedido` (`idPedido` ASC),
  INDEX `idCliente` (`idCliente` ASC),
  CONSTRAINT `factura_ibfk_1`
    FOREIGN KEY (`idCliente`)
    REFERENCES `enterprise`.`cliente` (`idCliente`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `factura_ibfk_2`
    FOREIGN KEY (`idPedido`)
    REFERENCES `enterprise`.`pedido` (`idPedido`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `enterprise`.`lista_articulos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `enterprise`.`lista_articulos` (
  `idListaArticulos` INT(11) NOT NULL AUTO_INCREMENT,
  `idArticulo` INT(11) NOT NULL,
  `idCliente` INT(11) NOT NULL,
  `cantidad` INT(11) NOT NULL,
  `estatusListaArticulos` CHAR(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`idListaArticulos`),
  INDEX `idArticulos` (`idArticulo` ASC),
  INDEX `idPedido` (`idCliente` ASC),
  CONSTRAINT `lista_articulos_ibfk_1`
    FOREIGN KEY (`idArticulo`)
    REFERENCES `enterprise`.`articulo` (`idArticulo`),
  CONSTRAINT `lista_articulos_ibfk_2`
    FOREIGN KEY (`idCliente`)
    REFERENCES `enterprise`.`cliente` (`idCliente`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `enterprise`.`perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `enterprise`.`perfil` (
  `idPerfil` INT(11) NOT NULL AUTO_INCREMENT,
  `perfil` VARCHAR(25) NOT NULL,
  `estatusPerfil` CHAR(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`idPerfil`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `enterprise`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `enterprise`.`usuario` (
  `idUsuario` INT(11) NOT NULL AUTO_INCREMENT,
  `idPersona` INT(11) NOT NULL,
  `username` VARCHAR(34) NOT NULL,
  `pass` VARCHAR(65) NOT NULL,
  `estatusUsuario` CHAR(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`idUsuario`),
  INDEX `idPersona` (`idPersona` ASC),
  CONSTRAINT `usuario_ibfk_1`
    FOREIGN KEY (`idPersona`)
    REFERENCES `enterprise`.`persona` (`idPersona`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 21
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `enterprise`.`perfil_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `enterprise`.`perfil_usuario` (
  `idUsuarioPerfil` INT(11) NOT NULL AUTO_INCREMENT,
  `idUsuario` INT(11) NOT NULL,
  `idPerfil` INT(11) NOT NULL,
  `estatusPerfilUsuario` CHAR(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`idUsuarioPerfil`),
  INDEX `idUsuario` (`idUsuario` ASC),
  INDEX `idPerfil` (`idPerfil` ASC),
  CONSTRAINT `perfil_usuario`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `enterprise`.`usuario` (`idUsuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `perfil_usuario_2`
    FOREIGN KEY (`idPerfil`)
    REFERENCES `enterprise`.`perfil` (`idPerfil`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `enterprise`.`sessions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `enterprise`.`sessions` (
  `session_id` VARCHAR(128) COLLATE 'utf8mb4_bin' NOT NULL,
  `expires` INT(11) UNSIGNED NOT NULL,
  `data` MEDIUMTEXT COLLATE 'utf8mb4_bin' NULL DEFAULT NULL,
  PRIMARY KEY (`session_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `enterprise`.`ticket_soporte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `enterprise`.`ticket_soporte` (
  `idticketSoporte` INT(11) NOT NULL AUTO_INCREMENT,
  `idPedido` INT(11) NOT NULL DEFAULT '0',
  `tituloTicket` VARCHAR(45) NULL DEFAULT NULL,
  `descripcionSoporte` VARCHAR(45) NULL DEFAULT NULL,
  `causaTicketSoporte` VARCHAR(45) NULL DEFAULT NULL,
  `estatusTicket` CHAR(1) NULL DEFAULT '1',
  PRIMARY KEY (`idticketSoporte`),
  INDEX `fk_ticket_soporte_pedido1_idx` (`idPedido` ASC),
  CONSTRAINT `fk_ticket_soporte_pedido1`
    FOREIGN KEY (`idPedido`)
    REFERENCES `enterprise`.`pedido` (`idPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
